import './assets/font/iconfont'
import './assets/style/nier.scss'
export { default as NrSwitch, } from './componets/Switch.vue'
export { default as NrButton, } from './componets/Button.vue'
export { default as NrTabs, } from './componets/Tabs.vue'
export { default as NrTab, } from './componets/Tab.vue'
export { default as NrDialog, } from './componets/Dialog.vue'
export { openDialog, } from './componets/openDialog'
export { default as NrProgress, } from './componets/Progress.vue'
export { default as NrCard, } from './componets/Card.vue'
export { default as NrCarousel, } from './componets/Carousel.vue'
export { default as NrCarouselItem, } from './componets/CarouselItem.vue'
