import './assets/font/iconfont'
import './assets/style/nier.scss'
export { default as NrSwitch, } from './componets/basic/Switch.vue'
export { default as NrButton, } from './componets/basic/Button.vue'
export { default as NrTabs, } from './componets/basic/Tabs.vue'
export { default as NrTab, } from './componets/basic/Tab.vue'
export { default as NrDialog, } from './componets/advanced/Dialog.vue'
export { openDialog, } from './componets/advanced/openDialog'
export { default as NrProgress, } from './componets/advanced/Progress.vue'
export { default as NrCard, } from './componets/advanced/Card.vue'
export { default as NrCarousel, } from './componets/advanced/Carousel.vue'
export { default as NrCarouselItem, } from './componets/advanced/CarouselItem.vue'
